In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
a1=np.array([1,2,3,4,5,6,7,8,9,10])
print(a1)
new_array=a1.reshape(2,5)                  
print(new_array)
print(new_array.shape)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [5]:
array = np.arange(1, 21)
array
extracted_elements = array[5:15]
array, extracted_elements

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))

In [7]:
import pandas as pd
fruits = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
print(fruits)
# Adding a new item 'pears' with the value 4
fruits['pears'] = 4
fruits

apples     3
bananas    2
oranges    1
dtype: int64


apples     3
bananas    2
oranges    1
pears      4
dtype: int64

In [13]:
import pandas as pd
import numpy as np
details= pd.DataFrame({
    'name': ["Siva","Anju","Malu","sruthi","afsal","sabith","jenni","pranav","mittel","dhyan"],
    'age': [26,25,24,30,45,25,35,25,24,29],
    'gender':["female","female","female","female","male","male","female","male","male","female"]
    },columns=['name','age','gender'])

details.index=[1,2,3,4,5,6,7,8,9,10]
details

name  age  gender
1     Siva   26  female
2     Anju   25  female
3     Malu   24  female
4   sruthi   30  female
5    afsal   45    male
6   sabith   25    male
7    jenni   35  female
8   pranav   25    male
9   mittel   24    male
10   dhyan   29  female

In [15]:
details["Occupation"] = ["Programmer", "Manager", "Analyst","Developer","Senior analyst",
                         "Marketing manager","Junior developer","Programmer","System analyst","Business analyst"]
details

name  age  gender         Occupation
1     Siva   26  female         Programmer
2     Anju   25  female            Manager
3     Malu   24  female            Analyst
4   sruthi   30  female          Developer
5    afsal   45    male     Senior analyst
6   sabith   25    male  Marketing manager
7    jenni   35  female   Junior developer
8   pranav   25    male         Programmer
9   mittel   24    male     System analyst
10   dhyan   29  female   Business analyst

In [17]:
details["age"]>=30

1     False
2     False
3     False
4      True
5      True
6     False
7      True
8     False
9     False
10    False
Name: age, dtype: bool

In [19]:
details.to_csv("final_details.csv")

data=pd.read_csv("final_details.csv")

In [22]:
details

name  age  gender         Occupation
1     Siva   26  female         Programmer
2     Anju   25  female            Manager
3     Malu   24  female            Analyst
4   sruthi   30  female          Developer
5    afsal   45    male     Senior analyst
6   sabith   25    male  Marketing manager
7    jenni   35  female   Junior developer
8   pranav   25    male         Programmer
9   mittel   24    male     System analyst
10   dhyan   29  female   Business analyst